models/alert.py
from typing import Dict
import uuid
from dataclasses import dataclass, field
from models.item import Item
from models.model import Model
from models.user import User
from libs.mailgun import Mailgun


@dataclass(eq=False)
class Alert(Model):
    collection: str = field(init=False, default='alerts')
    name: str
    item_id: str
    price_limit: float
    user_email: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)
        self.user = User.find_by_email(self.user_email)

    def json(self) -> Dict:
        return {
            'name': self.name,
            'item_id': self.item_id,
            'price_limit': self.price_limit,
            'user_email': self.user_email,
            '_id': self._id
        }

    def load_item_price(self) -> float:
        self.item.load_price()
        return self.item.price

    def notify_if_price_reached(self):
        if self.item.price < self.price_limit:
            print(
                f'Item {self.item} has reached {self.item.price} in price, and is now below {self.price_limit}.')
            Mailgun.send_mail(
                ['lentmiien@gmail.com'],
                f'Notification for {self.name}',
                f'Your alert {self.name} has reached a price under {self.price_limit}. The latest price is {self.item.price}. Go to the address to check your item: {self.item.url}',
                f'<p>Your alert {self.name} has reached a price under {self.price_limit}.</p><p>The latest price is {self.item.price}.</p><p>Click <a href="{self.item.url}">here</a> to purchase your item.</p>'
                )

views/alerts.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from models.item import Item
from models.alert import Alert
from models.store import Store
from models.user import requires_login

alert_bluprint = Blueprint('alerts', __name__)


@alert_bluprint.route('/')
@requires_login
def index():
    alerts = Alert.find_many_by('user_email', session['email'])
    return render_template('alerts/index.html', alerts=alerts)


@alert_bluprint.route('/new', methods=['GET', 'POST'])
@requires_login
def new_alert():
    if request.method == 'POST':
        name = request.form['name']
        item_url = request.form['item_url']
        price_limit = float(request.form['price_limit'])

        store = Store.find_by_url(item_url)
        item = Item(item_url, store.tag_name, store.query)
        item.load_price()
        item.save_to_mongo()

        Alert(name, item._id, price_limit, session['email']).save_to_mongo()

    return render_template('alerts/new_alert.html')


@alert_bluprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)

    if request.method == 'POST':
        alert.price_limit = float(request.form['price_limit'])
        alert.save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('alerts/edit_alert.html', alert=alert)


@alert_bluprint.route('/delete/<string:alert_id>')
@requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if alert.user_email == session['email']:
        alert.remove_from_mongo()
    return redirect(url_for('.index'))

templates/alerts/edit_alert.html
{% extends "base.html" %} {% block content %}
<header>
  <h1>Update Alert</h1>
</header>
<section class="update-item-form">
  <form method="post">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" value="{{ alert.name }}" disabled />
    </div>
    <div class="form-group">
      <label for="item_url">Item URL</label>
      <input type="text" class="form-control" id="item_url" name="item_url" value="{{ alert.item.url }}" disabled />
    </div>
    <div class="form-group">
      <label for="price_limit">Price Limit</label>
      <input
        type="number"
        class="form-control"
        id="price_limit"
        name="price_limit"
        placeholder="120.50"
        value="{{ alert.price_limit }}"
        aria-describedby="priceLimitHelp"
      />
      <small id="priceLimitHelp" class="form-text text-muted">
        Specify your price limit for when you will receive alerts for this item.
      </small>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
</section>
{% endblock %}

templates/alerts/index.html
{% extends "base.html" %} {% block content %}
<header>
  <h1>Alerts</h1>
</header>
<section>
  <div class="list-group mb-3">
    {% for alert in alerts %}
    <div class="list-group-item">
      <h4>{{ alert.name }}</h4>
      <p>
        <a href="{{ alert.item.url }}">{{ alert.item.url }}</a> (last price ${{ alert.item.price }})
      </p>
      <a href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" class="btn btn-secondary">Edit</a>
      <a href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" class="btn btn-danger">Delete</a>
    </div>
    {% endfor %}
  </div>
  <a href="{{ url_for('alerts.new_alert') }}" class="btn btn-primary">
    Create new
  </a>
</section>
{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %} {% block content %}
<header>
  <h1>Create Alert</h1>
</header>
<section class="create-item-form">
  <form method="post">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Item name" />
    </div>
    <div class="form-group">
      <label for="item_url">Item URL</label>
      <input type="text" class="form-control" id="item_url" name="item_url" placeholder="https://..." />
    </div>
    <div class="form-group">
      <label for="price_limit">Price Limit</label>
      <input
        type="number"
        class="form-control"
        id="price_limit"
        name="price_limit"
        placeholder="120.50"
        aria-describedby="priceLimitHelp"
      />
      <small id="priceLimitHelp" class="form-text text-muted">
        Specify your price limit for when you will receive alerts for this item.
      </small>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
</section>
{% endblock %}