models/store.py
from typing import Dict
from dataclasses import dataclass, field
import uuid
import re
from models.model import Model


@dataclass(eq=False)
class Store(Model):
    collection: str = field(init=False, default='stores')
    name: str
    url_prefix: str
    tag_name: str
    query: Dict
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def json(self) -> Dict:
        return {
            'name': self.name,
            'url_prefix': self.url_prefix,
            'tag_name': self.tag_name,
            'query': self.query,
            '_id': self._id
        }

    @classmethod
    def get_by_name(cls, store_name: str) -> 'Store':
        return cls.find_one_by('name', store_name)

    @classmethod
    def get_by_url_prefix(cls, url_prefix: str) -> 'Store':
        url_regex = {'$regex': '^{}'.format(url_prefix)}
        return cls.find_one_by('url_prefix', url_regex)

    @classmethod
    def find_by_url(cls, url: str) -> 'Store':
        pattern = re.compile(r'(https?://.*?/)')
        match = pattern.search(url)
        url_prefix = match.group(1)
        return cls.get_by_url_prefix(url_prefix)

views/stores.py
import json
from flask import Blueprint, render_template, request, redirect, url_for
from models.store import Store
from models.user import requires_login, requires_admin

store_bluprint = Blueprint('stores', __name__)


@store_bluprint.route('/')
@requires_login
def index():
    stores = Store.all()
    return render_template('stores/index.html', stores=stores)


@store_bluprint.route('/new', methods=['GET', 'POST'])
@requires_admin
def new_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

    return render_template('stores/new_store.html')


@store_bluprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@requires_admin
def edit_store(store_id):
    store = Store.get_by_id(store_id)

    if request.method == 'POST':
        store.url_prefix = request.form['url_prefix']
        store.tag_name = request.form['tag_name']
        store.query = json.loads(request.form['query'])
        store.save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/edit_store.html', store=store)


@store_bluprint.route('/delete/<string:store_id>')
@requires_admin
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for('.index'))

templates/stores/edit_store.html
{% extends "base.html" %} {% block content %}
<header>
    <h1>Update Store</h1>
</header>
<section class="update-item-form">
    <form method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ store.name }}" disabled />
        </div>
        <div class="form-group">
            <label for="url_prefix">URL Prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://..." value="{{ store.url_prefix }}" />
        </div>
        <div class="form-group">
            <label for="tag_name">Tag Name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="{{ store.tag_name }}"
                aria-describedby="tagNameHelp" />
            <small id="tagNameHelp" class="form-text text-muted">
                Specify the tag that holds the price.
            </small>
        </div>
        <div class="form-group">
            <label for="query">Query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "price"}' value="{{ store.query }}"
                aria-describedby="queryHelp" />
            <small id="queryHelp" class="form-text text-muted">
                Specify the query that will help find the correct tag.
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</section>
{% endblock %}

templates/stores/index.html
{% extends "base.html" %} {% block content %}
<header>
  <h1>Stores</h1>
</header>
<section>
  <div class="list-group mb-3">
    {% for store in stores %}
    <div class="list-group-item">
      <h4 class="list-group-item-heading">{{ store.name }}</h4>
      <p>
        For URLs starting with <a href="{{ store.url_prefix }}">{{ store.url_prefix }}</a
        >.
      </p>
      {% if session['email'] == config.ADMIN %}
      <a href="{{ url_for('stores.edit_store', store_id=store._id) }}" class="btn btn-secondary">Edit</a>
      <a href="{{ url_for('stores.delete_store', store_id=store._id) }}" class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
    {% endfor %}
  </div>
  {% if session['email'] == config.ADMIN %}
  <a href="{{ url_for('stores.new_store') }}" class="btn btn-primary">
    Create new
  </a>
  {% endif %}
</section>
{% endblock %}

templates/stores/new_store.html
{% extends "base.html" %} {% block content %}
<header>
  <h1>Create Store</h1>
</header>
<section class="create-item-form">
  <form method="post">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Store name" />
    </div>
    <div class="form-group">
      <label for="url_prefix">URL Prefix</label>
      <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://..." />
    </div>
    <div class="form-group">
      <label for="tag_name">Tag Name</label>
      <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" aria-describedby="tagNameHelp" />
      <small id="tagNameHelp" class="form-text text-muted">
        Specify the tag that holds the price.
      </small>
    </div>
    <div class="form-group">
      <label for="query">Query</label>
      <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "price"}' aria-describedby="queryHelp" />
      <small id="queryHelp" class="form-text text-muted">
        Specify the query that will help find the correct tag.
      </small>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
</section>
{% endblock %}